### ISSUE TITLE
Last active (viewed) step

### ISSUE THREAD

**Issue by kalicki** [devrnt/react-use-wizard#104]
Return the last viewed/active step

Eg:
Step1 - viewed
Step2 - viewed
Step3 - current (active)
Step4 - viewed (prev active)

I went to step 4 and returned to step 3 so 4 was the last seen

**Comment by devrnt** [comment]
Hi, could you provide some more context or a reproduction?

**Comment by 5ebastianMeier** [comment]
@kalicki if you only need the last one instead of a full history you could achieve it by handing over `activeStep` to a hook like [usePrevious](https://usehooks.com/usePrevious/)
