### ISSUE TITLE
Add possibility to customize stepCount or wrap context children

### ISSUE THREAD

**Issue by Luc9802** [devrnt/react-use-wizard#118]
I need to wrap my steps into a common wrapper which needs itself to access the context too.
Example:
```js
// Example: show the active step in the header
const Header = () => <p>I am the header component</p>;

// Example: show the "previous" and "next" buttons in the footer
const Footer = () => <p>I am the footer component</p>;

const App = () => {
  return (
    <Wizard startIndex={0} header={<Header />} footer={<Footer />}>
        <StepWrapper> {/* <-- This needs to access context too. */}
           <Step1 />
           <Step2 />
           <Step3 />
        </StepWrapper>
    </Wizard>
  );
};
```

But looking at the context code `stepCount` is retrieved in this way so:

 `const stepCount = React.Children.toArray(children).length;`

So in the example provided `stepCount` results to be 1 because it considers only `StepWrapper` as child.

The needed feature should be the possibility to manually customize this value or something to define a steps wrapper able to access context.

Is this something possible to do? Thank you.

**Comment by Luc9802** [comment]
Found this merge request #86 that probably addresses the issue.

**Comment by devrnt** [comment]
Fixed by #86

**Comment by devrnt** [comment]
Fixed by #86

**Comment by devrnt** [comment]
https://github.com/devrnt/react-use-wizard/releases/tag/v2.2.0

**Comment by Luc9802** [comment]
@devrnt I was testing v2.2.0, Is there a reason why header and footer are excluded from wrapper?

**Comment by devrnt** [comment]
It was introduced focused on the animation use case. It doesn't make much sense to animate the footer (probably previous/next buttons) or header

**Comment by Luc9802** [comment]
Got it, probably I had to explain better my needs.
My target was to be able to extend somehow the context provided with another context of additional info useful for my wizard.

For example in order to handle an info about the steps in error state I thought to do something like this: 

```js
export function AdditionalWizardContextProvider({ startIndex, header, footer, children, ...props }) {
	const [errorSteps, setErrorSteps] = useState([]);

	const stepHasError = useCallback(
		(stepIdx) => errorSteps.includes(stepIdx),
		[errorSteps]
	);

	const contextValue = useMemo(
		() => ({
			errorSteps,
			setErrorSteps,
			stepHasError
		}),
		[
			errorSteps,
			setErrorSteps,
			stepHasError
		]
	);

	return (
		<Wizard
			startIndex={startIndex}
			header={header}
			footer={footer}
			wrapper={<AdditionalWizardContextProvider.Provider value={contextValue} />}
		>
			{children}
		</Wizard>
	);
}
```

The usage would be something like this: 

```js
			<AdditionalWizardContextProvider
				header={<WizardStepper {...StepperProps} />}
				footer={<WizardStepButtons onSubmit={onSubmit} />}
			>
				<Step1/>
				<Step2/>
			</AdditionalWizardContextProvider>
```


Error info would be accessed and displayed directly from WizardStepper component and this info would be just one of the things I want to handle in my customized context. I didn't want to force the library to do something that is not recognized as a value and didn't want to re-do the very well done job already offered by it.

I hope this makes sense to you and it doesn't sound like a customization gone too far.
