### ISSUE TITLE
How to made a Vertical header? 

### ISSUE THREAD

**Issue by ChenReuven** [devrnt/react-use-wizard#120]
As far as I see the header is only horizontal on top of the steps.

Is there a way to use the header in a **vertical** direction? 

Thanks

**Comment by devrnt** [comment]
Hi, thanks for creating this issue. At the moment there is not. Note that you can still supply your own `<Step />` where you can design and position everything to your needs.

**Comment by ChenReuven** [comment]
> Hi, thanks for creating this issue. At the moment there is not. Note that you can still supply your own `<Step />` where you can design and position everything to your needs.

Thanks men, the library is great.

Can I create a PR with two mode:
1. Default - horizontal as today
2. Vertical

Is it will help?

Thanks, appriciate your work :-)

**Comment by devrnt** [comment]
Thanks for the appreciation! 

Sorry but I won't merge the PR, this library doesn't focus on UI (See [features](https://github.com/devrnt/react-use-wizard#features) "No UI restrictions"). Having the `header` and `footer` prop is already an encore.

Anyway thanks for the suggestion, I appreciate the initiative
