### ISSUE TITLE
Types not properly exported

### ISSUE THREAD

**Issue by MichielDeMey** [devrnt/react-use-wizard#126]
Looks like not all types are properly exported in the `package.json`.

We're using https://github.com/import-js/eslint-import-resolver-typescript/ which will try to resolve types based on the `exports` definition in the `package.json` file.

However, the types such as `WizardProps` are defined in a separate `types.d.ts` file which is not exported and cannot be found.

I believe we can simply add `"types": "./dist/types.d.ts"` to the `package.json` file to resolve this?

**Comment by devrnt** [comment]
Indeed, we should export all the types. Adding `"types": "./dist/types.d.ts"` won't help as far as I can see

**Comment by devrnt** [comment]
[v2.2.1](https://github.com/devrnt/react-use-wizard/releases/tag/v2.2.1)
