### ISSUE TITLE
Last step does not execute `handleStep`.

### ISSUE THREAD

**Issue by MichielDeMey** [devrnt/react-use-wizard#127]
In our use case, the last step of the wizard is often the step where we have to save our data by sending an API call to our backend.

My initial thought was to use the `handleStep` property from the `useWizard` hook, so we can also enjoy the `isLoading` boolean and error handling.

Unfortunately, it looks like the last step never executes the `handleStep` function forcing us to circumvent the hook and implement our own function for executing an async function in the last step.

(And also implementing a second `isLoading` boolean)

Is this a known limitation of the library or did we stumble upon a bug?

**Comment by devrnt** [comment]
I understand your use case, but at the moment this is expected behaviour. `nextStep` will only be invoked when the wizard detects there is "a next step" (aka a child)

**Comment by devrnt** [comment]
I'll close this, feel free to re-open if you've any more questions
