### ISSUE TITLE
Steps are all rendered together when children of wizard is a fragment

### ISSUE THREAD

**Issue by mayakoneval** [devrnt/react-use-wizard#143]
Hello! I noticed when children wrapped in a fragment are passed to Wizard, the wizard is rendered three times one after another. 

Curious if there is a reason this is not supported or if it should be, thanks!

```
  <Wizard>
    <>
      <Step1 />
      <Step2 />
      <Step3 />
    </>
  </Wizard>
```

**Comment by devrnt** [comment]
Feel free to re-open if you have any more questions
