### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by screeny05** [devrnt/react-use-wizard#158]
I'm trying to use this package with astro@2.7.0.

Unfortunately astro is not able to import this package, due to this lint-error:

> /dist/react-use-wizard.esm.js is written in ESM, but is interpreted as CJS. Consider using the .mjs extension, e.g. ./dist/react-use-wizard.esm.mjs 

Source:

https://publint.dev/react-use-wizard@2.2.1

Greetings!

**Comment by heythisispaul** [comment]
Getting the same issue when trying to mock it in Jest.

**Comment by tonhao-dev** [comment]
I'm getting the same problem when I try run a unit test

**Comment by devrnt** [comment]
Fixed in https://github.com/devrnt/react-use-wizard/pull/167

**Comment by devrnt** [comment]
[v.2.2.2](https://github.com/devrnt/react-use-wizard/releases/tag/v2.2.2)
