### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by flowck** [devrnt/react-use-wizard#168]
Hello,
I've just ran into the following issue while attempting to test with Jest a component that uses `react-use-wizard`: 

```
Details:

.../node_modules/react-use-wizard/dist/react-use-wizard.mjs:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { createContext, useContext, memo, useState, useRef, Children, useMemo, isValidElement, cloneElement, createElement } from 'react';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

Any advice on how to proceed from here?

![jest_config_js_—_web-ng](https://github.com/devrnt/react-use-wizard/assets/1679333/ab8bed6d-0c9f-4a14-824f-cd38b68daf2e)

**Comment by flowck** [comment]
I ended up solving the issue aforementioned with the following Jest config: 

```js
// jest.config.js
const config = {
    moduleNameMapper: {
        'react-use-wizard': '<rootDir>/node_modules/react-use-wizard/dist/react-use-wizard.cjs.production.min.js',
    }
}
```

**Comment by devrnt** [comment]
Thanks for letting this know. Can you provide which version of `react-use-wizard` you are using?

**Comment by firatgh** [comment]
Hi @devrnt, thanks for your reply.

I am using the version `2.2.3`, other parts of the stack are:

- Next.js 13.4.5
- Jest 29.6.1

Cheers,
Firmino

**Comment by flowck** [comment]
Hi @devrnt, thanks for your reply.

I am using the version `2.2.3`, other parts of the stack are:

- Next.js 13.4.5
- Jest 29.6.1

Cheers,
Firmino

**Comment by xta** [comment]
thanks @flowck your code worked. I'm also using `v2.2.3` and was having the `SyntaxError: Cannot use import statement outside a module` error in jest
