### ISSUE TITLE
reference step by key / identifier

### ISSUE THREAD

**Issue by matreu** [devrnt/react-use-wizard#170]
Right now the navigation is only possibly by numbers (index of step as child). However, wouldn't it be nice to have reference each step by name. That especially makes sense if you have a dynamic rendered sequence of steps and you want to jump around conditionally.
Similar like in this library: https://www.npmjs.com/package/react-albus

**Comment by devrnt** [comment]
Thanks for your feature request. I'm not planning to introduce this feature, it's out of scope. `react-use-wizard` exposes a `<Wizard>` component and it is up to the end-user to introduce the "step" component
