### ISSUE TITLE
Can't import the named export 'Children' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by saisilinus** [devrnt/react-use-wizard#171]
Hi,
I tried using this library but I keep getting the error `Can't import the named export 'Children' from non EcmaScript module (only default export is available)`.

**Expected behavior**: The app should compile

I've checked out the error and came across a similar question [Can't import the named export XXXX from non EcmaScript module (only default export is available)](https://stackoverflow.com/questions/69343038/cant-import-the-named-export-xxxx-from-non-ecmascript-module-only-default-expo). It seems the issue could be Webpack or react-scripts. 

Have you faced this issue before and if so, how did you resolve it?

**Comment by devrnt** [comment]
Please provide a reproduction, closing for now
