### ISSUE TITLE
Improve documentation for the "wrapper" prop

### ISSUE THREAD

**Issue by Ali762** [devrnt/react-use-wizard#184]
Explain how to use the wrapper with some simple examples. 

For example, if each step needed to be wrapped in a `<div className="flex-grow">`

**Comment by devrnt** [comment]
Hi, you can find an example [here](https://github.com/devrnt/react-use-wizard/blob/main/playground/modules/wizard/animated/index.tsx#L15). If the usage of `wrapper` is not clear enough, you're welcome to submit a pull request

**Comment by devrnt** [comment]
The [animated example](https://github.com/devrnt/react-use-wizard/blob/main/playground/modules/wizard/animated/index.tsx) should work for you
