### ISSUE TITLE
Issue with going to specific step using 'nextStep' when we are at last step

### ISSUE THREAD

**Issue by shabith** [devrnt/react-use-wizard#63]
Hi there!

When we are at the final step of the wizard, and if we want to go to a specific step, that functionality is not working.

I have created a small demo in [codesandbox](https://codesandbox.io/s/shy-star-l97b5?file=/pages/index.js)

So I did debug the code, and it seems like the issue here.
https://github.com/devrnt/react-use-wizard/blob/main/src/wizard.tsx#L20

```ts
    const goToNextStep = React.useRef((stepIndex?: number) => {
      if (hasNextStep.current) { // <-- this line
        setActiveStep((activeStep) => stepIndex ?? activeStep + 1);
      }
    });
```

Is there any way to overcome this issue?

**Comment by devrnt** [comment]
However that you pointed out a valid bug, your codesandbox is "working" as expected. `nextStep` takes an optional index, however, this starts at 0. So in the codesandbox it should say `nextStep(1)` , but this won't because of this issue.
