### ISSUE TITLE
FR: functionality to get total steps 

### ISSUE THREAD

**Issue by flyfishMT** [devrnt/react-use-wizard#87]
Is there a way to get the number of steps?  Something like this? Thanks

```
const Header = () => {
   const { activeStep, numberSteps } = useWizard();
   return (
     <h1>Step {activeStep + 1} of {numberSteps}</h1>
  );
};
```

**Comment by ulken** [comment]
> Is there a way to get the number of steps?

Not at the moment. But hopefully [soon](https://github.com/devrnt/react-use-wizard/pull/90).

**Comment by devrnt** [comment]
Hi, thanks for creating this issue (and already submitting a PR @ulken). 

See PR for follow-up

**Comment by ulken** [comment]
@devrnt Sure thing. Maybe you typed ahead, cause I can't see any comments on the PR, yet?

**Comment by devrnt** [comment]
[2.1.0](https://github.com/devrnt/react-use-wizard/releases/tag/v2.1.0)
