### ISSUE TITLE
Deprecation warning on Node 16

### ISSUE THREAD

**Issue by ulken** [devrnt/react-use-wizard#89]
Running `yarn test` (plausibly other script commands as well) outputs:

```shell
(node:80178) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/ulken/dev/react-use-wizard/node_modules/tsdx/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
```

I've read up a little on it and from what I can tell so far, it doesn't seem to be as easy as the suggested fix above. Fixing it in one version breaks it in another etc.

Just figured it should be tracked so it can be picked up when time's available.

**Comment by devrnt** [comment]
Hi, thanks for this heads up.
I've come across this warning as well. However, I'll close it since it's not breaking anything
